name: Build and Deploy

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

              # If you remove this step then you should probably remove the enable_jekyll option in the next one
            - name: Making latestVersion.json Public
              run: |
                  mkdir .dist
                  cp package.json .dist/latestVersion.json
                  cp .github/pages.html .dist/404.html
                  

              # Documentation: https://github.com/peaceiris/actions-gh-pages
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./.dist
                  # Makes it so the md files in the previous step get processed by GitHub Pages
                  enable_jekyll: true
                  # https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site
                  # This creates the CNAME file required to host github pages on a custom domain
                  # Remove this to use default [username].github.io domain
                  # Reminder: using a free domain service like freenom *can* result in your users getting hacked
                  # cname: kckarnige.is-a.dev