name: Draft Prerelease # Stole this from ArmCord
on:
  workflow_dispatch

env:
  FORCE_COLOR: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Node dependencies
        run: pnpm i
        
      - name: Install asar
        run: pnpm i @electron/asar -g

      - name: Build
        run: pnpm build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app.asar
          path: .dist/app.asar

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: app.asar
          path: release

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'devbuildversion'

      - name: Create the release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.version.outputs.prop}}-prerelease
          name: '[Prerelease] Oculus Dummy - ${{steps.version.outputs.prop}}'
          draft: true
          prerelease: true
          body_path: .github/prerelease.md
          files: |
            release/app.asar
